language: java
jdk:
  - oraclejdk8
script:
- mvn test

before_script:
  -   "export DISPLAY=:99.0"
  -   "sh -e /etc/init.d/xvfb start"
  -   sleep 3 # give xvfb some time to start
#addons:
#  firefox: "50.0.2"

after_failure:
 - cat $TRAVIS_BUILD_DIR/target/surefire-reports/*
 - echo "Current directory is $(pwd)"
 - echo "\n=== SUREFIRE REPORTS ===\n"
 - for F in target/surefire-reports/*.txt;do echo $F;cat $F;echo ;done
notifications:
  email:
    recipients:
      - deepak.gupta@tothenew.com   
    on_success: always
    on_failure: always
