language: java
jdk:
  - oraclejdk8
notifications:
  email:
    recipients:
      - Deepak.gupta@tothenew.com   
    on_success: always
    on_failure: always 
sudo: required  
dist: trusty 
script: phantomjs testrunner.js

