language: java
jdk:
  - oraclejdk8

before_script:
 - export CHROME_BIN=/usr/bin/google-chrome
 - sudo apt-get update
 - sudo apt-get install -y libappindicator1 fonts-liberation
 - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 - sudo dpkg -i google-chrome*.deb
 - xvfb -ac :99 -screen 0 1280x1024x16
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start

after_failure:
 - cat $TRAVIS_BUILD_DIR/target/surefire-reports/*
 - echo "Current directory is $(pwd)"
 - echo "\n=== SUREFIRE REPORTS ===\n"
 - for F in target/surefire-reports/*.txt;do echo $F;cat $F;echo ;done
notifications:
  email:
    recipients:
      - deepak.gupta@tothenew.com   
    on_success: always
    on_failure: always
