language: java
jdk:
  - oraclejdk8
sudo: required  
dist: trusty
before_install:
- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -	ac -screen 0 1280x1024x16"
after_failure:
 - echo "Current directory is $(pwd)"
 - echo "\n=== SUREFIRE REPORTS ===\n"
 - for F in target/surefire-reports/*.txt;do echo $F;cat $F;echo ;done
notifications:
  email:
    recipients:
      - deepak.gupta@tothenew.com   
    on_success: always
    on_failure: always
