language: java
jdk:
  - oraclejdk8
sudo: required  
dist: trusty
before_install:
 - export CHROME_BIN=/usr/bin/google-chrome
 - xvfb -ac :99 -screen 0 1280x1024x16 &
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start

after_failure:
 - echo "Current directory is $(pwd)"
 - echo "\n=== SUREFIRE REPORTS ===\n"
 - for F in target/surefire-reports/*.txt;do echo $F;cat $F;echo ;done
notifications:
  email:
    recipients:
      - deepak.gupta@tothenew.com   
    on_success: always
    on_failure: always
