language: java
jdk:
  - oraclejdk8
script:
- mvn clean package

before_script:
  - sudo wget --directory-prefix=/tmp http://ftp.mozilla.org/pub/firefox/releases/46.0.1/linux-x86_64/en-US/firefox-46.0.1.tar.bz2
  - sudo tar -xjf /tmp/firefox-46.0.1.tar.bz2 -C /usr/local/bin/firefoxhack --strip-components=1
  - export PATH="/usr/local/bin/firefoxhack:$PATH"
  -   "export DISPLAY=:99.0"
  -   "sh -e /etc/init.d/xvfb start"
  -   sleep 3 # give xvfb some time to start
addons:
  firefox: "49.0"

after_failure:
 - cat $TRAVIS_BUILD_DIR/target/surefire-reports/*
 - echo "Current directory is $(pwd)"
 - echo "\n=== SUREFIRE REPORTS ===\n"
 - for F in target/surefire-reports/*.txt;do echo $F;cat $F;echo ;done
notifications:
  email:
    recipients:
      - deepak.gupta@tothenew.com   
    on_success: always
    on_failure: always
