language: java
jdk:
  - oraclejdk8
script:
- mvn test
sudo: required
dist: trusty
addons:
 firefox: "48.0"
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- export CHROME_BIN=$(which google-chrome-stable)
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

notifications:
  email:
    recipients:
      - deepak.gupta@tothenew.com   
    on_success: always
    on_failure: always
