language: java
jdk:
  - oraclejdk8
notifications:
  email:
    recipients:
      - Deepak.gupta@tothenew.com   
    on_success: always
    on_failure: always 
sudo: required  
dist: trusty 
before_install: 
 - export CHROME_BIN=/usr/bin/chromedriver
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start



